// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPalWFUWVphkdlOa-L4HxjD-__t78sDVo',
    appId: '1:1028389526578:web:76a3066f424d70e925302b',
    messagingSenderId: '1028389526578',
    projectId: 'hoestella-c3e71',
    authDomain: 'hoestella-c3e71.firebaseapp.com',
    storageBucket: 'hoestella-c3e71.firebasestorage.app',
    measurementId: 'G-JM31LQDGK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC69ZxhBEtE2Piyz7bp4jLuId7VJgo2-1w',
    appId: '1:1028389526578:android:6f0b8dd187020b3d25302b',
    messagingSenderId: '1028389526578',
    projectId: 'hoestella-c3e71',
    storageBucket: 'hoestella-c3e71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'hoestella-c3e71',
    storageBucket: 'hoestella-c3e71.appspot.com',
  );
}